import io
import uuid
import datetime
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL

from app.models.analysis import ClaimAnalysisResult, AnalysisWorkflow
from app.services.storage import upload_to_r2, get_presigned_url

class AnalysisExportService:
    """
    Service for generating formal Legal Claim Charts in DOCX format.
    Fulfills 'DOCX Export' and 'Grid-style element mapping' requirements.
    """

    async def generate_claim_chart(
        self, 
        workflow: AnalysisWorkflow, 
        claims: list[ClaimAnalysisResult], 
        db_session
    ) -> str:
        """
        Generates a professional 3-column claim chart.
        Saves to R2 and returns a 15-minute signed URL.
        """
        doc = Document()
        
        # 1. Header & Title
        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title.add_run(f"CONFIDENTIAL ATTORNEY WORK PRODUCT\n{workflow.analysis_type.upper()} ANALYSIS: {workflow.id}")
        run.bold = True
        run.font.size = Pt(14)
        
        doc.add_paragraph(f"Date: {datetime.date.today().strftime('%B %d, %Y')}")
        doc.add_paragraph(f"Patent ID: {workflow.patent_id}")
        doc.add_paragraph("\n")

        # 2. Results Table
        # Columns: Element of Claim | Accused Product / Prior Art | Technical Assessment
        table = doc.add_table(rows=1, cols=3)
        table.style = 'Table Grid'
        
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Patent Claim Element / Limitation'
        hdr_cells[1].text = 'Corresponding Feature / Disclosure'
        hdr_cells[2].text = 'Analysis / Finding'
        
        # Style header
        for cell in hdr_cells:
            for paragraph in cell.paragraphs:
                run = paragraph.runs[0]
                run.bold = True

        for res in claims:
            # Add a row for the Claim Title
            row = table.add_row()
            cell = row.cells[0]
            cell.merge(row.cells[2])
            run = cell.paragraphs[0].add_run(f"CLAIM {res.claim_number}")
            run.bold = True
            
            # Add element-by-element rows
            for mapping in res.element_mappings:
                row = table.add_row()
                row.cells[0].text = mapping.get("element", "N/A")
                row.cells[1].text = mapping.get("product_feature", mapping.get("disclosure", "Not Found"))
                
                status = mapping.get("status", "Unknown").upper()
                notes = mapping.get("notes", "")
                row.cells[2].text = f"[{status}]\n{notes}"

        # 3. Footer
        doc.add_paragraph("\n\nDisclaimer: This analysis is generated by AI for technical assistance and does not constitute a legal opinion.")

        # 4. Save to R2
        target_stream = io.BytesIO()
        doc.save(target_stream)
        file_bytes = target_stream.getvalue()
        
        r2_key = f"reports/{workflow.firm_id}/{workflow.id}_chart.docx"
        await upload_to_r2(file_bytes, r2_key, content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        
        # Update workflow record
        workflow.report_r2_key = r2_key
        workflow.status = "completed"
        
        # Return 15m signed URL
        return await get_presigned_url(r2_key, expires_in=900)

analysis_export_service = AnalysisExportService()
