"""
Citation validation service.

After the LLM generates a response using strict RAG, this module:
1. Extracts all [Source: ...] citations from the output
2. Cross-references them against the actual chunks provided in the prompt
3. Detects uncited legal claims (statements that sound authoritative but lack citations)
4. Returns a validation report for the UI trust panel

This is an ADVISORY pass — it never blocks output, only flags issues.
"""

import re
from typing import List, Optional, TypedDict


class CitationValidationResult(TypedDict):
    is_valid: bool
    total_citations: int
    valid_citations: List[str]
    invalid_citations: List[str]
    uncited_claims: List[str]
    attorney_review_items: List[str]
    warning: bool


# ── Citation Extraction ─────────────────────────────────────────────────────

# Pattern: [Source: MPEP § 2111 — Claim Interpretation]
# or: [Source: 35 U.S.C. § 112, Written Description]
_CITATION_PATTERN = re.compile(r'\[Source:\s*([^\]]+)\]', re.IGNORECASE)

# Pattern: [ATTORNEY REVIEW REQUIRED: reason]
_REVIEW_PATTERN = re.compile(
    r'\[ATTORNEY REVIEW REQUIRED:\s*([^\]]+)\]', re.IGNORECASE
)

# Patterns that indicate legal claims which SHOULD be cited
_LEGAL_CLAIM_INDICATORS = [
    re.compile(r'\bpursuant to\b', re.IGNORECASE),
    re.compile(r'\bin accordance with\b', re.IGNORECASE),
    re.compile(r'\bas required by\b', re.IGNORECASE),
    re.compile(r'\bunder (?:35|37|28)\s*U\.?S\.?C', re.IGNORECASE),
    re.compile(r'\bunder (?:Rule|Article|Art\.?)\s*\d+', re.IGNORECASE),
    re.compile(r'\bMPEP\s*§?\s*\d+', re.IGNORECASE),
    re.compile(r'\bthe statute requires\b', re.IGNORECASE),
    re.compile(r'\bthe rule (?:requires|states|provides)\b', re.IGNORECASE),
    re.compile(r'\baccording to (?:the )?(?:MPEP|statute|guidelines?|rules?)\b', re.IGNORECASE),
    re.compile(r'\bmust (?:comply with|satisfy|meet)\b', re.IGNORECASE),
    re.compile(r'\b(?:is|are) required under\b', re.IGNORECASE),
]


def validate_citations(
    llm_output: str,
    legal_chunks: List[dict],
) -> CitationValidationResult:
    """
    Validate that citations in LLM output match the provided legal sources.

    Args:
        llm_output: The full text generated by the LLM.
        legal_chunks: The legal source chunks that were provided in the prompt context.

    Returns:
        CitationValidationResult with validity status and detailed breakdown.
    """
    # 1. Extract all citations from the output
    cited_sources = _CITATION_PATTERN.findall(llm_output)

    # 2. Build set of valid source references from what was actually provided
    valid_source_refs = set()
    for chunk in legal_chunks:
        title = chunk.get("source_title", chunk.get("title", ""))
        section = chunk.get("section", "")
        if title and section:
            valid_source_refs.add(f"{title}, {section}")
            valid_source_refs.add(f"{title} — {section}")
            # Also match partial references (just title or just section)
            valid_source_refs.add(title)
            valid_source_refs.add(section)
        elif title:
            valid_source_refs.add(title)

    # 3. Classify each citation as valid or invalid
    valid_citations = []
    invalid_citations = []

    for citation in cited_sources:
        citation_clean = citation.strip()
        # Check if citation matches any valid source reference
        is_valid = any(
            ref.lower() in citation_clean.lower() or citation_clean.lower() in ref.lower()
            for ref in valid_source_refs
        )
        if is_valid:
            valid_citations.append(citation_clean)
        else:
            invalid_citations.append(citation_clean)

    # 4. Detect uncited legal claims
    uncited_claims = _detect_uncited_claims(llm_output, cited_sources)

    # 5. Extract attorney review flags
    attorney_review_items = _REVIEW_PATTERN.findall(llm_output)

    # 6. Determine overall validity
    is_valid = len(invalid_citations) == 0
    has_warning = len(invalid_citations) > 0 or len(uncited_claims) > 0

    return CitationValidationResult(
        is_valid=is_valid,
        total_citations=len(cited_sources),
        valid_citations=valid_citations,
        invalid_citations=invalid_citations,
        uncited_claims=uncited_claims,
        attorney_review_items=attorney_review_items,
        warning=has_warning,
    )


def _detect_uncited_claims(
    llm_output: str,
    existing_citations: List[str],
) -> List[str]:
    """
    Scan for sentences that contain legal claim language but lack a citation.
    Uses heuristic patterns — not perfect, but catches obvious cases.
    """
    uncited = []

    # Split into sentences (simple heuristic)
    sentences = re.split(r'(?<=[.!?])\s+', llm_output)

    for sentence in sentences:
        # Skip if sentence already has a citation
        if _CITATION_PATTERN.search(sentence):
            continue

        # Check if sentence contains legal claim language
        for pattern in _LEGAL_CLAIM_INDICATORS:
            if pattern.search(sentence):
                # Truncate for display
                claim_preview = sentence[:150].strip()
                if len(sentence) > 150:
                    claim_preview += "..."
                uncited.append(claim_preview)
                break  # Only flag once per sentence

    return uncited[:10]  # Cap at 10 to avoid noise


def build_validation_summary(result: CitationValidationResult) -> str:
    """
    Build a human-readable summary of citation validation results.
    Used in SSE stream as the final [SOURCES] metadata event.
    """
    lines = []

    if result["is_valid"] and not result["uncited_claims"]:
        lines.append("✓ All citations verified against uploaded legal sources.")
    else:
        if result["invalid_citations"]:
            lines.append(
                f"⚠ {len(result['invalid_citations'])} citation(s) reference sources "
                f"not found in your uploaded legal materials."
            )
        if result["uncited_claims"]:
            lines.append(
                f"⚠ {len(result['uncited_claims'])} legal statement(s) detected without citations."
            )

    if result["attorney_review_items"]:
        lines.append(
            f"⚡ {len(result['attorney_review_items'])} point(s) flagged for attorney review."
        )

    lines.append(f"Total citations: {result['total_citations']}")
    return "\n".join(lines)
