import io
import uuid
from datetime import datetime
from typing import List, dict
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

async def generate_search_report_pdf(
    query: str,
    results: List[dict],
    firm_name: str = "PhronesisIP",
    attorney_name: str = "Attorney"
) -> io.BytesIO:
    """
    Generate a formal Prior Art Search Report as a PDF.
    Fulfills the 'Export results as PDF report' requirement.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=12,
        alignment=1 # Center
    )
    
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey
    )

    story = []

    # 1. Header & Title
    story.append(Paragraph(f"<b>{firm_name}</b> - Confidential Search Report", header_style))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", header_style))
    story.append(Spacer(1, 24))
    
    story.append(Paragraph("PRIOR ART SEARCH REPORT", title_style))
    story.append(Spacer(1, 12))
    
    # 2. Search Parameters
    story.append(Paragraph("<b>Search Parameters:</b>", styles['Heading2']))
    story.append(Paragraph(f"<b>Query:</b> {query}", styles['Normal']))
    story.append(Paragraph(f"<b>Attorney:</b> {attorney_name}", styles['Normal']))
    story.append(Spacer(1, 24))

    # 3. Results Summary Table
    story.append(Paragraph("<b>Search Findings:</b>", styles['Heading2']))
    
    data = [["Rank", "Patent Number", "Title", "Score", "Type"]]
    for i, r in enumerate(results[:20]): # Limit to top 20 for report
        data.append([
            str(i+1),
            r.get("patent_number", "N/A"),
            r.get("title", "N/A")[:50] + "...",
            f"{r.get('score', 0):.2f}",
            r.get("status", "Published")
        ])

    t = Table(data, colWidths=[40, 100, 250, 60, 80])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
    ]))
    story.append(t)
    story.append(Spacer(1, 24))

    # 4. Disclaimer
    disclaimer = """
    <b>Legal Disclaimer:</b> This report is generated by AI and is intended for preliminary prior art analysis only. 
    It does not constitute a formal legal opinion of non-infringement or validity. 
    The results are based on a combination of semantic similarity and technical ranking.
    """
    story.append(Paragraph(disclaimer, styles['Italic']))

    doc.build(story)
    buffer.seek(0)
    return buffer
